name: hook_ffff
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.0
  json_annotation: ^4.8.1
  dio: ^5.3.2
  equatable: ^2.0.5
  cookie_jar: ^4.0.8
  path_provider: ^2.1.1
  dio_cookie_manager: ^3.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail: ^1.0.0
flutter:
  generate: true
  uses-material-design: true